### ISSUE TITLE
Images zoom to bottom cente

### ISSUE THREAD

**Issue by Soitora** [tomik23/zooom.js#37]
Hey, all my images are zooming to the bottom middle if the page has enough content to make it scrollable, are you aware of a calculation that can be overwritten to fix this?

Thanks

![image](https://user-images.githubusercontent.com/10836780/151135394-33a093ae-9568-4e36-b409-d4bf31658d0f.png)

**Comment by tomik23** [comment]
And this is not due to the fact that this page has an iframe and there are pictures in it?

**Comment by Soitora** [comment]
> And this is not due to the fact that this page has an iframe and there are pictures in it?

I don't build the website, it's the site my company uses but it's so *ridicilously* badly coded so I use a Userscript to add features and correct a lot of stuff

They're not in a `<iframe>`, here's a quick look at the html elements
![image](https://user-images.githubusercontent.com/10836780/151178858-5da9c178-f2fe-4b63-8dfc-cd2c7ed08af8.png)

**Comment by tomik23** [comment]
Consequently, I have no idea what is wrong.
The question is whether you are able to put this html static html on http://codepen.io/ or some other page where I can download it and check what and how. Only that best with styles to reflect the problem.
From the pictures alone, I am not able to deduce what is wrong.

**Comment by Soitora** [comment]
> `Userscript` - This is some browser add-on that can be injected with other libraries? If so, then maybe that's the problem. The zooom library needs to be injected preferably at the end of the page. You can also try calling the library in this way.

Hmm works perfectly in the Codepen environment which is almost a carbon-copy, but not on the actual website
Probably has something to do with injecting it, I will do some experiments

**Comment by tomik23** [comment]
That's what I was afraid of, okay, I'm closing the thread for now.

PS. Check the link to this plugin and see how it works. Maybe there is a workaround for this problem.

**Comment by Soitora** [comment]
I'll try, thanks for the help so far
