### ISSUE TITLE
Inline styles are removed when exiting zoom

### ISSUE THREAD

**Issue by bodydisplaynone** [tomik23/zooom.js#41]
Steps to reproduce

1. Place an image with inline style:
![image](https://user-images.githubusercontent.com/22660372/160390332-ceb0fda0-3dc8-461f-aa3b-7b3e72d1d1fe.png)
2. Zoom in
3. Zoom out
4. Inline styles are removed as soon as the zoom out effect finishes
![image](https://user-images.githubusercontent.com/22660372/160390558-314ff435-9568-4804-8643-ee3d7a294aa1.png)

**Comment by tomik23** [comment]
Is it really a bug?
It is not good practice to use inline styles in html 😜

**Comment by bodydisplaynone** [comment]
I know, I just discovered this while testing. When using a bootstrap class or any template that uses proper helper classes like w-50 this does not happen, so only the style tag is affected. Maybe other attributes too..? Not sure about that but might be worth checking (e.g. data-).

**Comment by tomik23** [comment]
It should now be ok, the styles added remain in place.

**Comment by bodydisplaynone** [comment]
Cool, I just tested it and it works like a charm.
